name: Continuous integration

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  gha-test:
    name: GitHub Actions test
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          package-source: https://api.nuget.org/v3/index.json
          username: nuget
          install-cred-provider: true

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.token-info }}"

  node-test:
    name: Node.js test
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Test
        id: npm-test
        run: npm run test

  integration-test:
    name: Integration test
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      # - name: Setup .NET
      #   uses: actions/setup-dotnet@v3
      #   with:
      #     dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Publish
        run: dotnet publish --output ~/.nuget/plugins/netcore/NuGet.TokenCredentialProvider

      - uses: ./
        id: oidc-login
        with:
          username: jver
          package-source: https://jver-oidc.azurewebsites.net/api/v2/package
          install-cred-provider: false

      - name: Try delete
        run: dotnet nuget delete Knapcode.TorSharp 2.15.0 -s https://jver-oidc.azurewebsites.net/api/v2/package --non-interactive
        env:
          NUGET_TOKEN_INFO: ${{ steps.oidc-login.outputs.token-info }}
          NUGET_DANGEROUS_NO_REDACT: true

      - run: ls -R ~/.nuget/plugins
        if: always()

      - run: cat NuGet.TokenCredentialProvider.log
        if: always()

      - uses: actions/upload-artifact@v3
        with:
          name: my-log
          path: NuGet.TokenCredentialProvider.log
        if: always()

  # In TypeScript actions, `dist/` is a special directory. When you reference
  # an action with the `uses:` property, `dist/index.js` is the code that will be
  # run. For this project, the `dist/index.js` file is transpiled from other
  # source files. This workflow ensures the `dist/` directory contains the
  # expected transpiled code.
  #
  # If this workflow is run from a feature branch, it will act as an additional CI
  # check and fail if the checked-in `dist/` directory does not match what is
  # expected from the build.
  check-dist:
    name: Check dist for changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: install
        run: npm ci

      - name: Build dist/ Directory
        id: build
        run: npm run bundle

      # This will fail the workflow if the PR wasn't created by Dependabot.
      - name: Compare Directories
        id: diff
        run: |
          if [ "$(git diff --ignore-space-at-eol --text dist/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff --ignore-space-at-eol --text dist/
            exit 1
          fi

      # If `dist/` was different than expected, and this was not a Dependabot
      # PR, upload the expected version as a workflow artifact.
      - if: ${{ failure() && steps.diff.outcome == 'failure' }}
        name: Upload Artifact
        id: upload
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/
