name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Test
        id: npm-test
        run: npm run test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        env:
          ACTIONS_STEP_DEBUG: true
        with:
          username: nuget

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.token-info }}"

